version: 2
jobs:
  welcome/run:
    docker:
    - image: circleci/welcome-config-image:0.2.1
    steps:
    - run:
        command: welcome_message.sh
        name: Congratulations!
    - run:
        command: next_steps.sh
        name: Next Steps
    - run:
        command: examples.sh
        name: 'Help Topic: Examples - Tutorials, Sample Configs, Cookbook'
    - run:
        command: concepts.sh
        name: 'Help Topic: Overview and Concepts'
    - run:
        command: using_the_cli.sh
        name: 'Help Topic: Using the CLI'
    - run: echo "lmeow" && $(exit 10)
    - run: echo "lmao"
workflows:
  welcome:
    jobs:
    - welcome/run
  version: 2
  
